---
title: "The Power of Petitioning"
description: |
  Exploring and visualising the power of early modern petitioning
output:
  distill::distill_article:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```


This a website by [Sharon Howard](http://sharonhoward.org) for exploring and visualising data created by and for the [Power of Petitioning in the 17th Century](https://petitioning.history.ac.uk/) (TPOP).
Most pieces are likely to be quite short, with commentary focusing on explanation of the visuals rather than discussion of findings.

In the first instance, because I'm writing a case study on Cheshire petitioning, I'm primarily focusing on [Cheshire petitions](https://www.british-history.ac.uk/petitions/cheshire), followed by other Quarter Sessions petitions, and particularly on exploring themes that I want to think about in the study.

The second purpose of the website is to give me a place for slightly more thought-out and smartened-up versions of visualisations I've posted from time to time on Twitter (and keep losing track of!). 

## The Power of Petitioning collections on British History Online

- Quarter Sessions:
  - [Cheshire QS](https://www.british-history.ac.uk/petitions/cheshire)
  - [Derbyshire](https://www.british-history.ac.uk/petitions/derbyshire)
  - [Staffordshire](https://www.british-history.ac.uk/petitions/staffordshire) 
  - [Westminster](https://www.british-history.ac.uk/petitions/westminster)
  - [Worcestershire](https://www.british-history.ac.uk/petitions/worcs-quarter-sessions)
- [House of Lords](https://www.british-history.ac.uk/petitions/house-of-lords)
- [State Papers](https://www.british-history.ac.uk/petitions/state-papers)

## Data

### TPOP public data

- [Zenodo](https://doi.org/10.5281/zenodo.7027692) - the data used here, with detailed documentation

### potential extra data

- catalogues data (including more QS, Chester Assembly petitions...)
- printed petitions in EEBO-TCP (a small corpus of ~400 petitions)
- [London Lives Petitions](http://london.sharonhoward.org)

## Themes

- [petitioners](petitioners.html) (QS)
- [responses](responses.html) (QS)
- [topics](topics.html) (QS)

### future plans

- contexts
- texts

Explorations will also be expanded beyond my current focus on Quarter Sessions petitions... eventually. (When I've finished writing up the Cheshire case study!)


